#!/usr/bin/env python3
"""Generate a compact bright-star asset for the solar-system canvas."""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import math
import textwrap
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


CATALOG_URL = "https://cdsarc.cds.unistra.fr/ftp/V/50/catalog.gz"
README_URL = "https://cdsarc.cds.unistra.fr/ftp/V/50/ReadMe"
SOURCE_NAME = "Bright Star Catalogue, 5th Revised Ed. (CDS V/50)"
SOURCE_CITATION = "Hoffleit D., Warren Jr. W.H. 1991, Astronomical Data Center, NSSDC/ADC"
J2000_OBLIQUITY_DEG = 23.4392911
DEFAULT_MAG_LIMIT = 6.5


def _field(line: str, start: int, end: int) -> str:
    """Return a 1-indexed inclusive fixed-width field from a CDS record."""
    return line[start - 1 : end].strip()


def _to_float(value: str) -> float | None:
    try:
        return float(value)
    except ValueError:
        return None


def _to_int(value: str) -> int | None:
    try:
        return int(value)
    except ValueError:
        return None


def _parse_record(line: str, mag_limit: float) -> dict[str, Any] | None:
    hr = _to_int(_field(line, 1, 4))
    ra_h = _to_int(_field(line, 76, 77))
    ra_m = _to_int(_field(line, 78, 79))
    ra_s = _to_float(_field(line, 80, 83))
    dec_sign = _field(line, 84, 84)
    dec_d = _to_int(_field(line, 85, 86))
    dec_m = _to_int(_field(line, 87, 88))
    dec_s = _to_int(_field(line, 89, 90))
    vmag = _to_float(_field(line, 103, 107))

    if None in (hr, ra_h, ra_m, ra_s, dec_d, dec_m, dec_s, vmag):
        return None
    if vmag is None or vmag > mag_limit:
        return None

    dec_multiplier = -1 if dec_sign == "-" else 1
    ra_deg = 15 * (ra_h + ra_m / 60 + ra_s / 3600)
    dec_deg = dec_multiplier * (dec_d + dec_m / 60 + dec_s / 3600)
    lambda_deg, beta_deg = _equatorial_to_ecliptic(ra_deg, dec_deg)

    b_v = _to_float(_field(line, 110, 114))
    name = _field(line, 5, 14)
    spectral_type = _field(line, 128, 147)

    return {
        "id": f"HR{hr}",
        "name": name or None,
        "lambdaDeg": round(lambda_deg, 4),
        "betaDeg": round(beta_deg, 4),
        "mag": round(vmag, 2),
        "bv": round(b_v, 2) if b_v is not None else None,
        "spectrum": spectral_type or None,
    }


def _equatorial_to_ecliptic(ra_deg: float, dec_deg: float) -> tuple[float, float]:
    ra = math.radians(ra_deg)
    dec = math.radians(dec_deg)
    eps = math.radians(J2000_OBLIQUITY_DEG)

    x_eq = math.cos(dec) * math.cos(ra)
    y_eq = math.cos(dec) * math.sin(ra)
    z_eq = math.sin(dec)

    x_ecl = x_eq
    y_ecl = math.cos(eps) * y_eq + math.sin(eps) * z_eq
    z_ecl = -math.sin(eps) * y_eq + math.cos(eps) * z_eq

    lambda_deg = math.degrees(math.atan2(y_ecl, x_ecl)) % 360
    beta_deg = math.degrees(math.asin(max(-1, min(1, z_ecl))))
    return lambda_deg, beta_deg


def _download_catalog() -> tuple[str, str]:
    with urllib.request.urlopen(CATALOG_URL, timeout=30) as response:
        compressed = response.read()
    checksum = hashlib.sha256(compressed).hexdigest()
    return gzip.decompress(compressed).decode("ascii"), checksum


def generate(output: Path, provenance: Path, mag_limit: float) -> None:
    catalog_text, source_sha256 = _download_catalog()
    stars = [
        record
        for line in catalog_text.splitlines()
        if (record := _parse_record(line, mag_limit)) is not None
    ]
    # Draw dim stars first and bright stars last without sorting in the renderer.
    stars.sort(key=lambda row: row["mag"], reverse=True)

    generated_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    payload = {
        "schema": 1,
        "source": SOURCE_NAME,
        "sourceUrl": CATALOG_URL,
        "readmeUrl": README_URL,
        "citation": SOURCE_CITATION,
        "generatedAtUtc": generated_at,
        "sourceSha256": source_sha256,
        "epoch": "J2000",
        "frame": "ecliptic",
        "projectionNote": (
            "Stars are catalog directions converted from J2000 equatorial "
            "coordinates to J2000 ecliptic longitude/latitude. They are not "
            "solar-system-plane positions."
        ),
        "magnitudeLimit": mag_limit,
        "count": len(stars),
        "stars": stars,
    }

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(payload, separators=(",", ":"), ensure_ascii=True) + "\n", encoding="utf-8")

    provenance.parent.mkdir(parents=True, exist_ok=True)
    provenance.write_text(
        textwrap.dedent(
            f"""\
            # Bright Star Asset Provenance

            Generated by `tools/astronomy/stars.py`.

            - Source: {SOURCE_NAME}
            - Source URL: {CATALOG_URL}
            - Source ReadMe: {README_URL}
            - Citation: {SOURCE_CITATION}
            - Retrieved/generated: {generated_at}
            - Source SHA-256: `{source_sha256}`
            - Magnitude limit: V <= {mag_limit}
            - Generated star count: {len(stars)}
            - Coordinate transform: J2000 equatorial RA/Dec to J2000 ecliptic longitude/latitude.

            The generated JSON is a compact derived UI asset for the solar-system canvas.
            It represents catalog star directions, not physical star positions inside the
            heliocentric ecliptic plane.
            """
        ),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        default="frontend/public/assets/astronomy/stars-bright-v1.json",
        type=Path,
        help="Path for the generated JSON asset.",
    )
    parser.add_argument(
        "--provenance",
        default="frontend/public/assets/astronomy/stars-bright-v1.provenance.md",
        type=Path,
        help="Path for the generated provenance note.",
    )
    parser.add_argument(
        "--mag-limit",
        default=DEFAULT_MAG_LIMIT,
        type=float,
        help="Inclusive visual magnitude limit.",
    )
    args = parser.parse_args()
    generate(args.output, args.provenance, args.mag_limit)


if __name__ == "__main__":
    main()
